name: Build kernel 6.8

on:
  push:
    branches:
      'main'
  workflow_dispatch:
  pull_request:
      'main'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt install build-essential linux-headers-6.8.0-1010-azure
          make build